env:
  global:
    - CC_TEST_REPORTER_ID=29e76027aff9e31c6659c65d05b106730d5e19348dd40ef8421245b261d1ca6e
language: ruby
rvm:
  - 2.7
  - 2.6
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
